#!/bin/bash
# ref: https://github.com/Jac-Zac/My-home-config/tree/master/.config/sketchybar

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

ICON_FONT="Menlo Nerd Font"
LABEL_FONT="JetBrains Mono"
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=40
  color="$TRANSPARENT"
  blur_radius=30
  border_width=0
  border_color="$BAR_BORDER_COLOR"
  shadow=off
  position=top
  sticky=on
  padding_right=0
  padding_left=0
  y_offset=1
  margin=10
  topmost=window
  corner_radius=5
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$ICON_FONT:Regular:18.0"
  icon.padding_left="$PADDINGS"
  icon.padding_right="$PADDINGS"
  label.font="$LABEL_FONT:Regular:12.0"
  label.padding_left="$PADDINGS"
  label.padding_right="$PADDINGS"
  padding_right="$PADDINGS"
  padding_left="$PADDINGS"
  background.height=30
  background.corner_radius=9
  background.border_width=0
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/input.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/currency.sh"
# source "$ITEM_DIR/cpu.sh"
# source "$ITEM_DIR/slack.sh"

# bracket for everything
status_bracket=(
  background.color="$BACKGROUND"
  blur_radius=30
)

group=(
  # cpu.top
  # cpu.percent
  # cpu.sys
  # cpu.user
  currency
  "Control Center,Sound"
  input
  wifi
  calendar
  time
)
sketchybar --add bracket status "${group[@]}"                       \
           --set status "${status_bracket[@]}"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
