#!/bin/bash
# ref: https://github.com/Jac-Zac/My-home-config/tree/master/.config/sketchybar

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons
source "$CONFIG_DIR/features.sh"

ITEM_DIR="$CONFIG_DIR/items"     # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

ICON_FONT="Menlo Nerd Font"
LABEL_FONT="JetBrains Mono"
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
if $ENABLED_CPU; then
  HELPER=git.felix.helper
  killall helper
  (cd $CONFIG_DIR/helper && make)
  $CONFIG_DIR/helper/helper $HELPER >/dev/null 2>&1 &
fi

# Setting up the general bar appearance of the bar
bar=(
  height="$SKETCHYBAR_BAR_HEIGHT"
  color="$BACKGROUND"
  blur_radius=30
  border_width=0
  border_color="$BAR_BORDER_COLOR"
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  topmost=window
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$ICON_FONT:Regular:18.0"
  icon.padding_left="$PADDINGS"
  icon.padding_right="$PADDINGS"
  label.font="$LABEL_FONT:Regular:12.0"
  label.padding_left="$PADDINGS"
  label.padding_right="$PADDINGS"
  padding_right="$PADDINGS"
  padding_left="$PADDINGS"
  background.height=30
  background.border_width=0
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# Left
# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/input.sh"
source "$ITEM_DIR/volume.sh"

if $ENABLED_CURRENCY; then
  source "$ITEM_DIR/currency.sh"
fi

if $ENABLED_CPU; then
  source "$ITEM_DIR/cpu.sh"
fi

if $ENABLED_SLACK; then
  source "$ITEM_DIR/slack.sh"
fi

# bracket for everything
status_bracket=(
  background.color="$TRANSPARENT"
)

group=()

if $ENABLED_CPU; then
  group+=(
    cpu.top
    cpu.percent
    cpu.sys
    cpu.user
  )
fi

if $ENABLED_CURRENCY; then
  group+=(
    currency
  )
fi

group+=(
  "Control Center,Sound"
  input
  wifi
  calendar
  time
)
sketchybar --add bracket status "${group[@]}" \
  --set status "${status_bracket[@]}"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
